### PR TITLE
Add properties to modules

### PR DESCRIPTION
**Pull request by mykohsu**
For #15

### CODE REVIEW

**Comment by joaompneves** [comment]
Whats your use case? Modules can't have properties in typescript AFAIK.

**Comment by mykohsu** [comment]
I don't have access to the source any more. I believe it's possible to
declare globals in any file when not using a module loader.

**Comment by joaompneves** [comment]
Oh, you mean exported module-level vars. Then these changes are not enough. 
Closing for now until the use case arises again.

**Comment by mykohsu** [comment]
Without a module loader / system there are no exports. You can simply
declare a var on the global scope.

The changes worked for me at the time.

**Pull request closed without merging**
